module ServiceInvoker
  
  # Generated by request builders, used by ServiceInvoker::Base.new
  class Request < AbstractMessage
    attr_reader :url
    attr_reader :method
    attr_reader :user
    attr_reader :password    
    
    VALID_KEYS = [:url, :method, :headers, :raw_data, :user, :password, :url_params]
    
    def initialize options = {}
      options.assert_valid_keys(VALID_KEYS)
      raise ArgumentError, "url option is required (for now)" unless options.include?(:url)
      
      @url = options[:url] || ''
      if(options[:url_params])
        @url += '?' + Util.make_url_params(options[:url_params])
      end
      @method = options[:method] || :get
      unless [:get, :put, :post, :delete].include? @method
        raise ArgumentError, "Method must be :get, :put, :post or :delete"
      end
      @user = options[:user]
      @password = options[:password] || ''

      initialize_package(options[:raw_data] || "", options[:headers] || {})
    end      
  end
end